apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DATABASE_URL
        - name: DATABASE_READ_URL
          valueFrom:
            secretKeyRef:
              name: database-read-secret
              key: DATABASE_READ_URL
              optional: true
        - name: LOGS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: logs-database-secret
              key: LOGS_DATABASE_URL
        - name: OPENSEARCH_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: opensearch-secret
              key: OPENSEARCH_CONNECTION_STRING
              optional: true
        - name: OPENSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: opensearch-secret
              key: OPENSEARCH_USERNAME
              optional: true
        - name: OPENSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opensearch-secret
              key: OPENSEARCH_PASSWORD
              optional: true
        - name: SPACES_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-secret
              key: SPACES_ACCESS_KEY
        - name: SPACES_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-secret
              key: SPACES_SECRET_KEY
        - name: SPACES_BUCKET
          valueFrom:
            secretKeyRef:
              name: spaces-secret
              key: SPACES_BUCKET
        - name: SPACES_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: spaces-secret
              key: SPACES_ENDPOINT
        - name: SPACES_REGION
          valueFrom:
            secretKeyRef:
              name: spaces-secret
              key: SPACES_REGION
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: VALKEY_URL
          valueFrom:
            secretKeyRef:
              name: valkey-secret
              key: VALKEY_URL
        - name: VALKEY_HOST
          valueFrom:
            secretKeyRef:
              name: valkey-secret
              key: VALKEY_HOST
        - name: VALKEY_PORT
          valueFrom:
            secretKeyRef:
              name: valkey-secret
              key: VALKEY_PORT
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: valkey-secret
              key: VALKEY_PASSWORD
        - name: NODE_ENV
          value: "development"
        - name: RP_ID
          value: "localhost"
        - name: FRONTEND_URL
          value: "http://localhost:5173"
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-secret
              key: SENDGRID_API_KEY
              optional: true
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: STRIPE_SECRET_KEY
              optional: true
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: STRIPE_PUBLISHABLE_KEY
              optional: true
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: STRIPE_WEBHOOK_SECRET
              optional: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        livenessProbe:
          httpGet:
            path: /graphql?query=%7B__typename%7D
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /graphql?query=%7B__typename%7D
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP