apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
      - name: prisma-migrate
        image: ghcr.io/thegildapp/monorepo/backend:latest
        imagePullPolicy: Always
        command: ["npx", "prisma", "migrate", "deploy"]
        workingDir: /app
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DATABASE_URL
      containers:
        - name: backend
          image: ghcr.io/thegildapp/monorepo/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_URL
            - name: LOGS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: logs-database-secret
                  key: LOGS_DATABASE_URL
            - name: OPENSEARCH_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: OPENSEARCH_CONNECTION_STRING
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: OPENSEARCH_USERNAME
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: OPENSEARCH_PASSWORD
            - name: SPACES_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-secret
                  key: SPACES_ACCESS_KEY
            - name: SPACES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-secret
                  key: SPACES_SECRET_KEY
            - name: SPACES_BUCKET
              valueFrom:
                secretKeyRef:
                  name: spaces-secret
                  key: SPACES_BUCKET
            - name: SPACES_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: spaces-secret
                  key: SPACES_ENDPOINT
            - name: SPACES_REGION
              valueFrom:
                secretKeyRef:
                  name: spaces-secret
                  key: SPACES_REGION
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
            - name: VALKEY_URL
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: VALKEY_URL
            - name: VALKEY_HOST
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: VALKEY_HOST
            - name: VALKEY_PORT
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: VALKEY_PORT
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: VALKEY_PASSWORD
            - name: RP_ID
              value: "thegild.app"
            - name: FRONTEND_URL
              value: "https://thegild.app"
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid-secret
                  key: SENDGRID_API_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
