apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secret
type: Opaque
stringData:
  OPENSEARCH_CONNECTION_STRING: "https://your-opensearch-endpoint:port"
  OPENSEARCH_USERNAME: "your-username"
  OPENSEARCH_PASSWORD: "your-password"