apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
stringData:
  STRIPE_SECRET_KEY: "sk_test_your_test_secret_key_here"
  STRIPE_PUBLISHABLE_KEY: "pk_test_your_test_publishable_key_here"
  STRIPE_WEBHOOK_SECRET: "whsec_your_webhook_secret_here"